# Generated by Django 3.1.1 on 2020-09-05 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome_number', models.CharField(max_length=2)),
                ('chromosome_initial_position', models.IntegerField()),
                ('chromosome_last_position', models.IntegerField()),
                ('symbol', models.CharField(max_length=20)),
                ('related_disease', models.ManyToManyField(to='GenApi.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome_number', models.CharField(max_length=2)),
                ('position', models.IntegerField()),
                ('id_variant', models.CharField(max_length=10)),
                ('reference', models.CharField(blank=True, max_length=20, null=True)),
                ('alternative', models.CharField(blank=True, max_length=20, null=True)),
                ('gen_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenApi.gen')),
            ],
        ),
    ]
