# Generated by Django 3.1.1 on 2020-09-05 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('chromosome_number', models.CharField(max_length=2)),
                ('position', models.IntegerField()),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=20, null=True)),
                ('alternative', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gen',
            fields=[
                ('chromosome_number', models.CharField(max_length=2)),
                ('chromosome_initial_position', models.IntegerField()),
                ('chromosome_last_position', models.IntegerField()),
                ('symbol', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('gen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_symbol', to='GenApi.variant')),
                ('related_disease', models.ManyToManyField(blank=True, to='GenApi.Disease')),
            ],
            options={
                'unique_together': {('gen', 'symbol')},
            },
        ),
    ]
